// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmoatawzcxejixhipvsb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtb2F0YXd6Y3hlaml4aGlwdnNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NzAxMTIsImV4cCI6MjA2NjM0NjExMn0.sFsaRvkDCt1oNzxSaK90DSNEewCZhP8hQ54WnfRd2as";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);